language: node_js

sudo: false

node_js:
  - '6'
cache: yarn

env:
  global:
  - CXX=g++-4.8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - yarn add global gulp karma eslint flow-bin
  - yarn install

script:
  - export NODE_ENV=production
  - eslint ./assets/**/*.js
  - karma start karma.conf.js
  - flow check
  - yarn build

after_success:
  - bash deploy.sh
