language: node_js

sudo: false

node_js:
  - '6'
cache: yarn

env:
  global:
  - CXX=g++-4.8
  - secure: e2fQteNKSHaVv5LPh9BeLcf0u4asvWk7AT0Yhpm32FBysW2rbL3l3aPrbY+CoNa+yQ0p5tq9h+jK19v4FbEYmFZFj4dgVSu6uBIUQ/6p1Muzn29E5p4mH9TW4uZ++nJ+Vqul+XAVVrO/E+RlD1POBQVWryjipnMsah53yfWBqEFRyZsb2eTuCxQ3/+x9cywZIBK3ZYi1CkwRNN+ryNAFo1Vcx3goDy0kTtzohW8kUunN+6heAeTTr2JT0lwoWvHxngIprl2D0GA5cRZY7cGAZI5LVih9dHDKIlAqllveGq61FN8g4sqVXmU3xcvz/L3f3cL1OESWqX31Lh2zO7vLcdlyVvbSNH7acllJAdWYHYzNIm0k1+9rUS5Fp49rGXgjMiIvPXdoQqO3s9/JWNYJRSm3IvbKH4/NUSUKAAyR/p93fMpCYmWHzRCygf896PLV9+V9Y5vQsmdpLhPgsSRjVgkCug6g1bUdYvv1wJ11NWUV3DhYIAcs4OGMfQEKOV8uGjvqWjUcb8S2mGZZov2T7jrxoE8DFYjy/1IFxJl8sjicKTtumsYFX+gIfLQ+KpSDbKBavF+S83yXHZeemf8ml8/6oTySRDfRfjjgN+SejolBWdfmHTs94QfN+Pi2+cjXdBEV0WLZ9FYJAhkIm8QLc1IcLMhzTPTC9YRxVQl6TCI=

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - yarn add global gulp karma eslint
  - yarn install

script:
  - NODE_ENV=production yarn build
  - yarn test

after_success:
  - bash deploy.sh
